import json

nb = {
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os, pathlib, datetime\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.gridspec import GridSpec\n",
    "\n",
    "DOWNLOADS_DIR = pathlib.Path('/mnt/c/Users/juana/Downloads').resolve()\n",
    "\n",
    "def safe_path(p):\n",
    "    try:\n",
    "        p.resolve().relative_to(DOWNLOADS_DIR)\n",
    "        return True\n",
    "    except ValueError:\n",
    "        return False\n",
    "\n",
    "assert DOWNLOADS_DIR.exists(), f'Path not found: {DOWNLOADS_DIR}'\n",
    "print(f'Target: {DOWNLOADS_DIR}')\n",
    "\n",
    "TODAY = datetime.date.today()\n",
    "records = []\n",
    "for entry in DOWNLOADS_DIR.iterdir():\n",
    "    if not safe_path(entry) or not entry.is_file():\n",
    "        continue\n",
    "    try:\n",
    "        stat = entry.stat()\n",
    "    except (PermissionError, OSError):\n",
    "        continue\n",
    "    ext = entry.suffix.lower() if entry.suffix else '(no ext)'\n",
    "    size_mb = stat.st_size / (1024**2)\n",
    "    modified = datetime.date.fromtimestamp(stat.st_mtime)\n",
    "    records.append({'filename': entry.name, 'extension': ext,\n",
    "                    'size_mb': round(size_mb, 3), 'date_modified': modified,\n",
    "                    'age_days': (TODAY - modified).days})\n",
    "\n",
    "df = pd.DataFrame(records)\n",
    "print(f'Files found: {len(df)}')\n",
    "print(df.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "ext_counts = df['extension'].value_counts()\n",
    "threshold = max(1, int(len(df) * 0.02))\n",
    "small_exts = ext_counts[ext_counts <= threshold].index\n",
    "pie_series = ext_counts.copy()\n",
    "pie_series['other'] = pie_series[small_exts].sum()\n",
    "pie_series = pie_series.drop(index=small_exts).sort_values(ascending=False)\n",
    "top_size = df.nlargest(15, 'size_mb')\n",
    "\n",
    "fig = plt.figure(figsize=(16, 12))\n",
    "fig.suptitle('Downloads Folder Audit', fontsize=18, fontweight='bold')\n",
    "gs = GridSpec(2, 2, figure=fig, hspace=0.45, wspace=0.35)\n",
    "\n",
    "ax_pie = fig.add_subplot(gs[0, 0])\n",
    "ax_pie.pie(pie_series.values, labels=pie_series.index, autopct='%1.1f%%',\n",
    "           startangle=140, colors=plt.cm.Set3.colors[:len(pie_series)])\n",
    "ax_pie.set_title('File Types by Count', fontweight='bold')\n",
    "\n",
    "ax_bar = fig.add_subplot(gs[0, 1])\n",
    "short_names = [n if len(n)<=28 else n[:25]+'...' for n in top_size['filename']]\n",
    "ax_bar.barh(short_names[::-1], top_size['size_mb'].values[::-1], color='steelblue')\n",
    "ax_bar.set_xlabel('Size (MB)')\n",
    "ax_bar.set_title('Top 15 Files by Size', fontweight='bold')\n",
    "ax_bar.tick_params(axis='y', labelsize=7)\n",
    "\n",
    "ax_old = fig.add_subplot(gs[1, 0])\n",
    "ax_old.axis('off')\n",
    "oldest = df.nlargest(10, 'age_days')[['filename','age_days','date_modified']].copy()\n",
    "oldest['filename'] = oldest['filename'].apply(lambda n: n if len(n)<=30 else n[:27]+'...')\n",
    "oldest['date_modified'] = oldest['date_modified'].astype(str)\n",
    "tbl = ax_old.table(cellText=oldest.values, colLabels=['Filename','Age (days)','Modified'],\n",
    "                   cellLoc='left', loc='center')\n",
    "tbl.auto_set_font_size(False)\n",
    "tbl.set_fontsize(7.5)\n",
    "tbl.auto_set_column_width([0,1,2])\n",
    "ax_old.set_title('10 Oldest Files', fontweight='bold', pad=12)\n",
    "\n",
    "ax_big = fig.add_subplot(gs[1, 1])\n",
    "ax_big.axis('off')\n",
    "biggest = df.nlargest(10, 'size_mb')[['filename','size_mb']].copy()\n",
    "biggest['filename'] = biggest['filename'].apply(lambda n: n if len(n)<=30 else n[:27]+'...')\n",
    "biggest['size_mb'] = biggest['size_mb'].apply(lambda v: f'{v/1024:.2f} GB' if v>=1024 else f'{v:.1f} MB')\n",
    "tbl2 = ax_big.table(cellText=biggest.values, colLabels=['Filename','Size'],\n",
    "                    cellLoc='left', loc='center')\n",
    "tbl2.auto_set_font_size(False)\n",
    "tbl2.set_fontsize(7.5)\n",
    "tbl2.auto_set_column_width([0,1])\n",
    "ax_big.set_title('10 Biggest Files', fontweight='bold', pad=12)\n",
    "\n",
    "plt.savefig('/tmp/downloads_audit_report.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()\n",
    "print('Chart saved to /tmp/downloads_audit_report.png')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "oversized = df[df['size_mb'] >= 1024].sort_values('size_mb', ascending=False)\n",
    "ancient   = df[df['age_days'] >= 365].sort_values('age_days', ascending=False)\n",
    "\n",
    "print('=' * 60)\n",
    "print(f'FILES OVER 1 GB ({len(oversized)} found)')\n",
    "print('=' * 60)\n",
    "for _, r in oversized.iterrows():\n",
    "    print(f\"  {r['size_mb']/1024:.2f} GB  |  {r['filename']}\")\n",
    "\n",
    "print()\n",
    "print('=' * 60)\n",
    "print(f'FILES OLDER THAN 365 DAYS ({len(ancient)} found)')\n",
    "print('=' * 60)\n",
    "for _, r in ancient.iterrows():\n",
    "    print(f\"  {r['age_days']} days  |  {r['date_modified']}  |  {r['filename']}\")\n",
    "\n",
    "print()\n",
    "print('Scan complete. Nothing was modified.')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.x.x"}
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open('/home/juana/miami-analysis/downloads_audit.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

print('Notebook created.')
